version: "3.9"

services:
  db:
    container_name: database
    build: ./database/
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - shared-network
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - shared-network
    ports:
      - 8080:8080

volumes:
  db-data:
    name: "database-data"

networks:
  shared-network:
    name: "shared-network"
